const HEXAGRAMS: Record<number, {
  name: string; symbol: string; upper: string; lower: string;
  lines: number[]; meaning: string; interpretation: string;
}> = {
  1: { name:'乾为天', symbol:'䷀', upper:'乾', lower:'乾', lines:[1,1,1,1,1,1], meaning:'元亨利贞', interpretation:'纯阳之卦，万物创始，刚健不息。占得此卦，大吉大利，诸事亨通。' },
  2: { name:'坤为地', symbol:'䷁', upper:'坤', lower:'坤', lines:[0,0,0,0,0,0], meaning:'元亨利牝马之贞', interpretation:'纯阴之卦，厚德载物。宜守不宜攻，宜静不宜动。' },
  3: { name:'水雷屯', symbol:'䷂', upper:'坎', lower:'震', lines:[1,0,0,0,1,0], meaning:'元亨利贞，勿用有攸往', interpretation:'万物始生，困难重重。宜积蓄力量，暂勿冒进。' },
  4: { name:'山水蒙', symbol:'䷃', upper:'艮', lower:'坎', lines:[0,1,0,0,0,1], meaning:'亨，匪我求童蒙', interpretation:'启蒙之卦，求学进取。时机未熟，需待开导。' },
  5: { name:'水天需', symbol:'䷄', upper:'坎', lower:'乾', lines:[1,1,1,0,1,0], meaning:'有孚光亨贞吉', interpretation:'需待时机，不可急躁。守正待时，自有转机。' },
  6: { name:'天水讼', symbol:'䷅', upper:'乾', lower:'坎', lines:[0,1,0,1,1,1], meaning:'有孚窒惕中吉', interpretation:'争讼之象，宜和解不宜对抗。退一步海阔天空。' },
  7: { name:'地水师', symbol:'䷆', upper:'坤', lower:'坎', lines:[0,1,0,0,0,0], meaning:'贞丈人吉无咎', interpretation:'师旅征战，宜谨慎谋划。统帅要贤明，方可取胜。' },
  8: { name:'水地比', symbol:'䷇', upper:'坎', lower:'坤', lines:[0,0,0,0,1,0], meaning:'吉，原筮元永贞', interpretation:'亲附之象，团结合作。与人亲近，互助成功。' },
  9: { name:'风天小畜', symbol:'䷈', upper:'巽', lower:'乾', lines:[1,1,1,0,1,1], meaning:'亨，密云不雨', interpretation:'小有积蓄，力量未足。蓄势待发，不宜大举。' },
  10: { name:'天泽履', symbol:'䷉', upper:'乾', lower:'兑', lines:[1,1,0,1,1,1], meaning:'履虎尾不咥人亨', interpretation:'如履薄冰，谨慎行事。遵循规矩，可化险为夷。' },
  11: { name:'地天泰', symbol:'䷊', upper:'坤', lower:'乾', lines:[1,1,1,0,0,0], meaning:'小往大来吉亨', interpretation:'天地交泰，万事亨通。阴阳和合，运势上扬。' },
  12: { name:'天地否', symbol:'䷋', upper:'乾', lower:'坤', lines:[0,0,0,1,1,1], meaning:'否之匪人不利', interpretation:'闭塞不通，小人当道。宜隐忍退守，等待时机。' },
  13: { name:'天火同人', symbol:'䷌', upper:'乾', lower:'离', lines:[1,0,1,1,1,1], meaning:'同人于野亨', interpretation:'志同道合，团结协作。广结善缘，共同进步。' },
  14: { name:'火天大有', symbol:'䷍', upper:'离', lower:'乾', lines:[1,1,1,1,0,1], meaning:'元亨', interpretation:'丰盛富有，大有所得。丰收之时，宜分享共赢。' },
  15: { name:'地山谦', symbol:'䷎', upper:'坤', lower:'艮', lines:[0,0,1,0,0,0], meaning:'亨，君子有终', interpretation:'谦虚之德，终有所成。满招损谦受益，持之以恒。' },
  16: { name:'雷地豫', symbol:'䷏', upper:'震', lower:'坤', lines:[0,0,0,1,0,0], meaning:'利建侯行师', interpretation:'愉悦安乐，顺势而为。享乐有度，不可放纵。' },
  17: { name:'泽雷随', symbol:'䷐', upper:'兑', lower:'震', lines:[1,0,0,1,1,0], meaning:'元亨利贞无咎', interpretation:'随顺时势，灵活应变。顺应自然，万事可成。' },
  18: { name:'山风蛊', symbol:'䷑', upper:'艮', lower:'巽', lines:[0,1,1,0,0,1], meaning:'元亨，利涉大川', interpretation:'除弊革新，整顿治理。发现问题及时纠正。' },
  19: { name:'地泽临', symbol:'䷒', upper:'坤', lower:'兑', lines:[1,1,0,0,0,0], meaning:'元亨利贞', interpretation:'居高临下，察看民情。运气渐佳，大有作为。' },
  20: { name:'风地观', symbol:'䷓', upper:'巽', lower:'坤', lines:[0,0,0,0,1,1], meaning:'盥而不荐有孚', interpretation:'观察审视，明辨是非。冷静旁观，静待时机。' },
  21: { name:'火雷噬嗑', symbol:'䷔', upper:'离', lower:'震', lines:[1,0,0,1,0,1], meaning:'亨利用狱', interpretation:'咬合咀嚼，克服障碍。以强硬手段解决问题。' },
  22: { name:'山火贲', symbol:'䷕', upper:'艮', lower:'离', lines:[1,0,1,0,0,1], meaning:'亨小利有攸往', interpretation:'装饰美化，注重外表。不可过分追求形式。' },
  23: { name:'山地剥', symbol:'䷖', upper:'艮', lower:'坤', lines:[0,0,0,0,0,1], meaning:'不利有攸往', interpretation:'剥落衰败，小人得势。宜隐忍退守保全自身。' },
  24: { name:'地雷复', symbol:'䷗', upper:'坤', lower:'震', lines:[1,0,0,0,0,0], meaning:'亨，出入无疾', interpretation:'一阳来复，万象更新。否极泰来，重新开始。' },
  25: { name:'天雷无妄', symbol:'䷘', upper:'乾', lower:'震', lines:[1,0,0,1,1,1], meaning:'元亨利贞', interpretation:'不妄为不强求，顺其自然。守正不妄行。' },
  26: { name:'山天大畜', symbol:'䷙', upper:'艮', lower:'乾', lines:[1,1,1,0,0,1], meaning:'利贞，不家食吉', interpretation:'大有积蓄，厚积薄发。学识积累，等待施展。' },
  27: { name:'山雷颐', symbol:'䷚', upper:'艮', lower:'震', lines:[1,0,0,0,0,1], meaning:'贞吉，观颐自求口实', interpretation:'颐养调养，养精蓄锐。自食其力，注意养生。' },
  28: { name:'泽风大过', symbol:'䷛', upper:'兑', lower:'巽', lines:[0,1,1,1,1,0], meaning:'栋桡，利有攸往亨', interpretation:'太过则反，物极必反。矫枉过正，反而有害。' },
  29: { name:'坎为水', symbol:'䷜', upper:'坎', lower:'坎', lines:[0,1,0,0,1,0], meaning:'有孚维心亨', interpretation:'险阻重重，内外皆险。坚守信念，渡过低谷。' },
  30: { name:'离为火', symbol:'䷝', upper:'离', lower:'离', lines:[1,0,1,1,0,1], meaning:'利贞亨，畜牝牛吉', interpretation:'光明依附，柔顺中正。保持光明心志可获吉祥。' },
  31: { name:'泽山咸', symbol:'䷞', upper:'兑', lower:'艮', lines:[0,0,1,1,1,0], meaning:'亨利贞取女吉', interpretation:'感应沟通，心灵相通。感情融洽，婚姻吉祥。' },
  32: { name:'雷风恒', symbol:'䷟', upper:'震', lower:'巽', lines:[0,1,1,1,0,0], meaning:'亨无咎利贞', interpretation:'恒久不变，持之以恒。守常不变，终有成果。' },
  33: { name:'天山遁', symbol:'䷠', upper:'乾', lower:'艮', lines:[0,0,1,1,1,1], meaning:'亨小利贞', interpretation:'退避退隐，韬光养晦。远离纷争保全自身。' },
  34: { name:'雷天大壮', symbol:'䷡', upper:'震', lower:'乾', lines:[1,1,1,1,0,0], meaning:'利贞', interpretation:'强盛壮大，蓬勃发展。守正用壮，不可恃强。' },
  35: { name:'火地晋', symbol:'䷢', upper:'离', lower:'坤', lines:[0,0,0,1,0,1], meaning:'康侯用锡马蕃庶', interpretation:'前进上升，事业发达。光明磊落可得晋升。' },
  36: { name:'地火明夷', symbol:'䷣', upper:'坤', lower:'离', lines:[1,0,1,0,0,0], meaning:'利艰贞', interpretation:'光明受损，身处黑暗。韬光养晦艰难度日。' },
  37: { name:'风火家人', symbol:'䷤', upper:'巽', lower:'离', lines:[1,0,1,0,1,1], meaning:'利女贞', interpretation:'家庭和睦，齐家之道。关注家庭内部事务。' },
  38: { name:'火泽睽', symbol:'䷥', upper:'离', lower:'兑', lines:[1,1,0,1,0,1], meaning:'小事吉', interpretation:'乖离不合，意见分歧。小事可成大事难合。' },
  39: { name:'水山蹇', symbol:'䷦', upper:'坎', lower:'艮', lines:[0,0,1,0,1,0], meaning:'利西南不利东北', interpretation:'行路艰难，寸步难行。知难而退另寻出路。' },
  40: { name:'雷水解', symbol:'䷧', upper:'震', lower:'坎', lines:[0,1,0,1,0,0], meaning:'利西南无所往', interpretation:'困难解开，舒缓解脱。冰消雪融春回大地。' },
  41: { name:'山泽损', symbol:'䷨', upper:'艮', lower:'兑', lines:[1,1,0,0,0,1], meaning:'有孚元吉无咎', interpretation:'损下益上，减损节制。以损求益反而增长。' },
  42: { name:'风雷益', symbol:'䷩', upper:'巽', lower:'震', lines:[1,0,0,0,1,1], meaning:'利有攸往利涉大川', interpretation:'增益丰盛，大有利益。付出努力会得回报。' },
  43: { name:'泽天夬', symbol:'䷪', upper:'兑', lower:'乾', lines:[1,1,1,1,1,0], meaning:'扬于王庭孚号有厉', interpretation:'决断果决，当断则断。果断决策不拖泥带水。' },
  44: { name:'天风姤', symbol:'䷫', upper:'乾', lower:'巽', lines:[0,1,1,1,1,1], meaning:'女壮勿用取女', interpretation:'不期而遇，邂逅相逢。意外相遇需保持警惕。' },
  45: { name:'泽地萃', symbol:'䷬', upper:'兑', lower:'坤', lines:[0,0,0,1,1,0], meaning:'亨王假有庙', interpretation:'聚集汇聚，人才荟萃。群英聚会团结协作。' },
  46: { name:'地风升', symbol:'䷭', upper:'坤', lower:'巽', lines:[0,1,1,0,0,0], meaning:'元亨用见大人', interpretation:'步步高升，循序渐进。脚踏实地稳步上升。' },
  47: { name:'泽水困', symbol:'䷮', upper:'兑', lower:'坎', lines:[0,1,0,1,1,0], meaning:'亨贞大人吉无咎', interpretation:'困顿艰难，四面受阻。守正不阿等待转机。' },
  48: { name:'水风井', symbol:'䷯', upper:'坎', lower:'巽', lines:[0,1,1,0,1,0], meaning:'改邑不改井', interpretation:'井养万物，源远流长。根本稳固无惧变迁。' },
  49: { name:'泽火革', symbol:'䷰', upper:'兑', lower:'离', lines:[1,0,1,1,1,0], meaning:'巳日乃孚元亨利贞', interpretation:'变革革新，除旧布新。改变之时顺势改革。' },
  50: { name:'火风鼎', symbol:'䷱', upper:'离', lower:'巽', lines:[0,1,1,1,0,1], meaning:'元吉亨', interpretation:'鼎新立异，建功立业。革故鼎新建功之时。' },
  51: { name:'震为雷', symbol:'䷲', upper:'震', lower:'震', lines:[1,0,0,1,0,0], meaning:'亨，震来虩虩', interpretation:'雷震天动，令人警醒。遇惊不慌临危不乱。' },
  52: { name:'艮为山', symbol:'䷳', upper:'艮', lower:'艮', lines:[0,0,1,0,0,1], meaning:'艮其背不获其身', interpretation:'止步知止，适可而止。知足不辱知止不殆。' },
  53: { name:'风山渐', symbol:'䷴', upper:'巽', lower:'艮', lines:[0,0,1,0,1,1], meaning:'女归吉利贞', interpretation:'渐进而行，徐徐图之。稳步推进不可急进。' },
  54: { name:'雷泽归妹', symbol:'䷵', upper:'震', lower:'兑', lines:[1,1,0,1,0,0], meaning:'征凶无攸利', interpretation:'少女归嫁，婚姻之事。顺其自然不可强求。' },
  55: { name:'雷火丰', symbol:'䷶', upper:'震', lower:'离', lines:[1,0,1,1,0,0], meaning:'亨王假之勿忧', interpretation:'丰盛富有，如日中天。盛极必衰居安思危。' },
  56: { name:'火山旅', symbol:'䷷', upper:'离', lower:'艮', lines:[0,0,1,1,0,1], meaning:'小亨旅贞吉', interpretation:'旅途在外，漂泊不定。行旅在外宜谨慎。' },
  57: { name:'巽为风', symbol:'䷸', upper:'巽', lower:'巽', lines:[0,1,1,0,1,1], meaning:'小亨利有攸往', interpretation:'柔顺谦逊，顺应自然。以柔克刚顺势而为。' },
  58: { name:'兑为泽', symbol:'䷹', upper:'兑', lower:'兑', lines:[1,1,0,1,1,0], meaning:'亨利贞', interpretation:'喜悦欢乐，和悦待人。以诚待人取信于人。' },
  59: { name:'风水涣', symbol:'䷺', upper:'巽', lower:'坎', lines:[0,1,0,0,1,1], meaning:'亨王假有庙', interpretation:'涣散离散，分离之时。聚合民心化解分歧。' },
  60: { name:'水泽节', symbol:'䷻', upper:'坎', lower:'兑', lines:[1,1,0,0,1,0], meaning:'亨苦节不可贞', interpretation:'节制约束，适可而止。过犹不及掌握分寸。' },
  61: { name:'风泽中孚', symbol:'䷼', upper:'巽', lower:'兑', lines:[1,1,0,0,1,1], meaning:'豚鱼吉利涉大川', interpretation:'诚信感化，以诚相待。至诚通天大事可成。' },
  62: { name:'雷山小过', symbol:'䷽', upper:'震', lower:'艮', lines:[0,0,1,1,0,0], meaning:'亨利贞可小事', interpretation:'小有过越，宜小不宜大。小事可为大事不宜。' },
  63: { name:'水火既济', symbol:'䷾', upper:'坎', lower:'离', lines:[1,0,1,0,1,0], meaning:'亨小利贞初吉终乱', interpretation:'事已成功，功德圆满。守成不易谨防复失。' },
  64: { name:'火水未济', symbol:'䷿', upper:'离', lower:'坎', lines:[0,1,0,1,0,1], meaning:'亨小狐汔济濡其尾', interpretation:'事未完成，有待努力。功败垂成需要坚持。' },
};

const LIUQIN_BY_YAO: Record<string, string[]> = {
  乾: ['父母','父母','父母','官鬼','官鬼','官鬼'],
  兑: ['父母','父母','官鬼','官鬼','官鬼','父母'],
  离: ['官鬼','官鬼','官鬼','父母','父母','父母'],
  震: ['官鬼','官鬼','父母','父母','父母','官鬼'],
  巽: ['父母','父母','父母','官鬼','官鬼','官鬼'],
  坎: ['官鬼','官鬼','父母','父母','父母','官鬼'],
  艮: ['父母','父母','父母','官鬼','官鬼','官鬼'],
  坤: ['官鬼','官鬼','官鬼','父母','父母','父母'],
};

const LIUSHEN = ['青龙','朱雀','勾陈','螣蛇','白虎','玄武'];

const SHIYAO: Record<number, number> = {
  1:5, 2:2, 3:0, 4:3, 5:4, 6:1, 7:2, 8:5,
  9:1, 10:4, 11:2, 12:4, 13:2, 14:4, 15:4, 16:0,
  17:2, 18:1, 19:1, 20:3, 21:4, 22:0, 23:4, 24:0,
  25:3, 26:1, 27:3, 28:2, 29:4, 30:5, 31:2, 32:2,
  33:1, 34:3, 35:3, 36:0, 37:1, 38:4, 39:3, 40:1,
  41:2, 42:2, 43:3, 44:0, 45:2, 46:5, 47:2, 48:4,
  49:2, 50:1, 51:4, 52:2, 53:1, 54:2, 55:4, 56:0,
  57:2, 58:4, 59:4, 60:0, 61:3, 62:1, 63:2, 64:4,
};
const YINGYAO_OFFSET = 3;

export { HEXAGRAMS, LIUQIN_BY_YAO, LIUSHEN, SHIYAO };
